# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_transfer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_transfer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12msg_transfer.proto\"\xd7\x01\n\x04Send\x12\x1b\n\x06inputs\x18\x01 \x03(\x0b\x32\x0b.Send.Input\x12\x1d\n\x07outputs\x18\x02 \x03(\x0b\x32\x0c.Send.Output\x1a&\n\x05Token\x12\r\n\x05\x64\x65nom\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\x1a\x34\n\x05Input\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12\x1a\n\x05\x63oins\x18\x02 \x03(\x0b\x32\x0b.Send.Token\x1a\x35\n\x06Output\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12\x1a\n\x05\x63oins\x18\x02 \x03(\x0b\x32\x0b.Send.Tokenb\x06proto3')
)




_SEND_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='Send.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='denom', full_name='Send.Token.denom', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='Send.Token.amount', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=129,
)

_SEND_INPUT = _descriptor.Descriptor(
  name='Input',
  full_name='Send.Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Send.Input.address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coins', full_name='Send.Input.coins', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=183,
)

_SEND_OUTPUT = _descriptor.Descriptor(
  name='Output',
  full_name='Send.Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Send.Output.address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coins', full_name='Send.Output.coins', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=238,
)

_SEND = _descriptor.Descriptor(
  name='Send',
  full_name='Send',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs', full_name='Send.inputs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='Send.outputs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SEND_TOKEN, _SEND_INPUT, _SEND_OUTPUT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=238,
)

_SEND_TOKEN.containing_type = _SEND
_SEND_INPUT.fields_by_name['coins'].message_type = _SEND_TOKEN
_SEND_INPUT.containing_type = _SEND
_SEND_OUTPUT.fields_by_name['coins'].message_type = _SEND_TOKEN
_SEND_OUTPUT.containing_type = _SEND
_SEND.fields_by_name['inputs'].message_type = _SEND_INPUT
_SEND.fields_by_name['outputs'].message_type = _SEND_OUTPUT
DESCRIPTOR.message_types_by_name['Send'] = _SEND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Send = _reflection.GeneratedProtocolMessageType('Send', (_message.Message,), dict(

  Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), dict(
    DESCRIPTOR = _SEND_TOKEN,
    __module__ = 'msg_transfer_pb2'
    # @@protoc_insertion_point(class_scope:Send.Token)
    ))
  ,

  Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), dict(
    DESCRIPTOR = _SEND_INPUT,
    __module__ = 'msg_transfer_pb2'
    # @@protoc_insertion_point(class_scope:Send.Input)
    ))
  ,

  Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), dict(
    DESCRIPTOR = _SEND_OUTPUT,
    __module__ = 'msg_transfer_pb2'
    # @@protoc_insertion_point(class_scope:Send.Output)
    ))
  ,
  DESCRIPTOR = _SEND,
  __module__ = 'msg_transfer_pb2'
  # @@protoc_insertion_point(class_scope:Send)
  ))
_sym_db.RegisterMessage(Send)
_sym_db.RegisterMessage(Send.Token)
_sym_db.RegisterMessage(Send.Input)
_sym_db.RegisterMessage(Send.Output)


# @@protoc_insertion_point(module_scope)
