# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stdTx_transfer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from binance_dex.tx_data_format import stdSignature_pb2 as stdSignature__pb2
from binance_dex.tx_data_format import msg_transfer_pb2 as msg__transfer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stdTx_transfer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14stdTx_transfer.proto\x1a\x12stdSignature.proto\x1a\x12msg_transfer.proto\"j\n\x05StdTx\x12\x12\n\x03msg\x18\x01 \x03(\x0b\x32\x05.Send\x12!\n\nsignatures\x18\x02 \x03(\x0b\x32\r.StdSignature\x12\x0c\n\x04memo\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x62\x06proto3')
  ,
  dependencies=[stdSignature__pb2.DESCRIPTOR,msg__transfer__pb2.DESCRIPTOR,])




_STDTX = _descriptor.Descriptor(
  name='StdTx',
  full_name='StdTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='StdTx.msg', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signatures', full_name='StdTx.signatures', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='StdTx.memo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='StdTx.source', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='StdTx.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=170,
)

_STDTX.fields_by_name['msg'].message_type = msg__transfer__pb2._SEND
_STDTX.fields_by_name['signatures'].message_type = stdSignature__pb2._STDSIGNATURE
DESCRIPTOR.message_types_by_name['StdTx'] = _STDTX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StdTx = _reflection.GeneratedProtocolMessageType('StdTx', (_message.Message,), dict(
  DESCRIPTOR = _STDTX,
  __module__ = 'stdTx_transfer_pb2'
  # @@protoc_insertion_point(class_scope:StdTx)
  ))
_sym_db.RegisterMessage(StdTx)


# @@protoc_insertion_point(module_scope)
